
# Common user generate test
POST http://127.0.0.1:5000/auth/join
content-type: application/json

{
    "username": "test1",
    "email": "sample@naver.com",
    "password": "test1234"
}

# Admin user generate
POST http://127.0.0.1:5000/auth/join
content-type: application/json

{
    "username": "test1",
    "email": "sample@naver.com",
    "password": "test1234",
    "role": "admin"
}